### ISSUE TITLE
Pulling threat detections

### ISSUE THREAD

**Issue by eldawt** [mcafee/mvision-edr-activity-feed#40]
Is there a way to pull EDR threat detections using this tool? 
When testing, I only receive empty payloads

**Comment by jmdacruz** [comment]
Hi there! yes, you should be able to consume threat detections using this tool. Can you provide some more detail on how you're launching the tool and which parameters you are using? Don't include credentials, obviously. It would also be helpful if you can attach an annotated version of the script you are using to subscribe to the events.

**Comment by jmdacruz** [comment]
Thanks for the info @eldawt. I think I know what the issue is: The `samples.individual` module only subscribes to `case` events (which are events triggered by cases on the investigation workspace). In your scenario, what you want to subscribe to are events of type `threats`. 

You can see an example of this on our syslog forwarder integration [here](https://github.com/mcafee/mvision-edr-activity-feed/blob/master/samples/syslog_forwarder/__init__.py#L41). For testing purposes, you can simply create a python script inside the `samples` folder with the following code:

```python
import logging
from mvision_edr_activity_feed import subscribe

@subscribe(entity='threat')
def threat_detected(event):
    logging.info("NEW THREAT: %s", event)
```

If you name the file `samples/my_threats.py`, then run the CLI as follows:

```shell
mvision-edr-activity-feed --url https://api.soc.mcafee.com/ --username xxxx --password xxxx --module samples.my_threats --loglevel=debug
```

Hope this helps!

**Comment by eldawt** [comment]
I created my_threats.py using the provided code above and placed it under samples/, when I try to run the command I receive the following output.

`CRITICAL:root:While attempting to load module 'samples.my_threats': No module named my_threats
2020-04-24 11:38:16,066;CRITICAL;While attempting to load module 'samples.my_threats': No module named my_threats`

is there a step I missed before running the command?
![Capture](https://user-images.githubusercontent.com/63120526/80234951-f9707f00-8626-11ea-95c5-f270204dbdab.PNG)

**Comment by jmdacruz** [comment]
Try the following: Create a top-level folder called `modules` (at the same level as `samples`, and move `my_threats.py` in there. Then run the CLI as follows:

```shell
mvision-edr-activity-feed --url https://api.soc.mcafee.com/ --username xxxx --password xxxx --module modules.my_threats --loglevel=debug
```

There is a bug: we seem to be packaging the `samples` folder into the install package, which means that `samples` is added as a top-level python package (and this will "shadow" the local `samples` directory when trying to load modules that are local). I'll create a bug to fix this.

**Comment by eldawt** [comment]
that solved the issue, I ran the command for a few minutes and it returned a json format threat payload, are the payloads any threats detected after I launch the command?

Thank you for your help jmdacruz

**Comment by jmdacruz** [comment]
Glad to hear! With regards to how the client consumes events, this API resembles the behavior of a Kafka consumer: The CLI uses a default value for the consumer group (can be modified with `--consumer-group`, run `mvision-edr-activity-feed --help` for more details). The first time you run the CLI, this consumer group will be created and configured to read the "latest" messages only. The API then maintains the state for the consumer group for a period of time (this is not yet exposed, but will be added), even if the client disconnects. Also, there is a PR (#39) so that you can choose whether to start from the "latest" or the "earliest" elements on the queue (this will be available via de `--reset` argument)

**Comment by eldawt** [comment]
Now that I have successfully pulled these threat details using the command line tool, what would you recommend as the best practice for ingesting new detentions into ESM?

**Comment by paguerre2** [comment]
[NOT AN ISSUE] Code under master repository doesn't shadows anything. I think it might be a confusion on loading or how the client uses the project. Team tested master code under different vms and there was not problem regarding showdows so Marcelo's is incorrect and further checks withe the particular client must be done (following splunk guid sample works in more than 10 tests vms without issues).
