### ISSUE TITLE
Missing events and hostname

### ISSUE THREAD

**Issue by eldawt** [mcafee/mvision-edr-activity-feed#43]
When pulling threat events, the tool is not receiving all events that I can see on the EDR monitoring dashboard, how can I achieve this?

Also, I currently do not receive the hostname in the threat event payload, is there a way that I can achieve this?

**Comment by paguerre2** [comment]
[AS DESIGNED] This isn't a BUG, instead if requested, this is a "feature" because originally it was decided to provide MGUID instead of IP or HOSTNAME for the Thteat event because MGUID represents the unique Id in MCAFEE of the NODE, that is the main information -u can log to MVISION EDR or MVISON ePO and find the Node IP associated to the thread by MGUID - (additionally IPs can be repeated in certain clone situations while MGUID should never be repeated).
Finally, AF is a proxy project that shows the information displayed in Threat topic so if there are lags or delays, or missing events this should be checked with DXL team or Pipeline service (this project is using official dxl streaming lib so @eldawt it's suggested to check lags problem).
